import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { getAllPlanets } from "../utils/api";
import { Planet } from "../utils/types";

import Image from 'next/image'

import { CriticalButton } from '@gjensidige/nci-core-buttons/lib/critical-button';
import { Title } from '@gjensidige/nci-core-typography/lib/title';
import { Text } from '@gjensidige/nci-core-typography/lib/text';
import { Container, Col, Row } from '@gjensidige/nci-core-grid/lib';
import { Input } from '@gjensidige/nci-core-forms/lib/input';
import { useState } from 'react';

interface Props {
  planets: Planet[];

}
const Home: NextPage<Props> = ({ planets }) => {
  const [searchResults, setSearchResults] = useState([]);
  const [searchInput, setSearchInput] = useState('');

  console.log("planets " + planets);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Title tag="h1">
            Planet wars
          </Title>
          <Row>
            <Col xxs={6}>
              <Input
                id="search-id"
                labelText="Search for planets"
                name="search-name"
                onChange={(event) => setSearchInput(event.currentTarget.value)}
                value={searchInput} />
              <CriticalButton>Search</CriticalButton>
            </Col>
          </Row>
          <Row>
            <Col as="ul">

            </Col>
          </Row>
        </Container>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  try {
    const data = await getAllPlanets();
    const planets = data.data.allPlanets.planets as Planet[];
    return { props: { planets } };
  } catch (error) {
    console.error("could not fetch planets", error);
  }

  // Pass data to the page via props
  return { props: null };
}

export default Home;
