import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { getAllPlanets } from "../utils/api";
import { Planet } from "../utils/types";

interface Props {
  planets: Planet[];
}

const Home: NextPage<Props> = ({ planets }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PlanetWars - Team Hav</title>
        <meta name="description" content="Generated by the Hav team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  try {
    const data = await getAllPlanets();
    const planets = data.data.allPlanets.planets as Planet[];
    return { props: { planets } };
  } catch (error) {
    console.error("could not fetch planets", error);
  }

  // Pass data to the page via props
  return { props: null };
}

export default Home;
