import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { getAllPlanets } from "../utils/api";

const Home: NextPage = ({ data }: any) => {
  console.log(data.locations);
  return (
    <div className={styles.container}>
      <Head>
        <title>PlanetWars - Team Hav</title>
        <meta name="description" content="Generated by the Hav team" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data.locations.map((item: any) => (
        <h1 key={item.id}>{item.name}</h1>
      ))}
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  try {
    const results = await getAllPlanets();
    const data = results.data;
    return { props: { data } };
  } catch (error) {
    console.error("could not fetch planets", error);
  }

  // Pass data to the page via props
  return { props: null };
}

export default Home;
